HealthDataBase/HealthDataBase/Controllers/AdminController.cs
using HealthDataBase.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthDataBase.Controllers
{
    /// <summary>
    /// Jaimin Patel
    /// This contoller contains the actions an admin can perform 
    /// </summary>
    public class AdminController : Controller
    {
        private IUserRepository _userRepo;
        public AdminController(IUserRepository userRepo)
        {
            _userRepo = userRepo;
        }
        // GET: Admin
        public ActionResult AdminHome()
        {
            Session["UserName"] = ViewBag.adminName;
            ViewBag.isAdmin = true;
            return View();
        }
        [HttpGet]
        public ActionResult AddNewUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddNewUser(users user)
        {
            if (ModelState.IsValid)
            {
                _userRepo.SaveUser(user);
            }
            return RedirectToAction("AdminHome");
        }
        public ActionResult ViewUsers()
        {
           Session["auth"] = true;
            Session["userList"] = _userRepo.UserList;
            return View("ViewUsers");
        }
        public ActionResult EditUserInfo(int userId)
        {
            users user = _userRepo.UserList.FirstOrDefault(u => u.UserId == userId);
            if(user != null)
            {
                return View(user);
            }
            return View("AdminHome");
        }

        public ActionResult SaveUser(users user)
        {
            if (ModelState.IsValid)
            {
                if(Request.Form["_btnSubmit"] == "Save Info")
                {
                    _userRepo.SaveUser(user);
                }
                else if(Request.Form["_btnSubmit"] == "Delete User")
                {
                    
                    _userRepo.DeleteUser(user.UserId);
                }
            }
            return RedirectToAction("ViewUsers");
        }
    }
}

HealthDataBase/HealthDataBase/Controllers/DoctorController.cs
using HealthDataBase.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
/// <summary>
/// Fahad Mirza
/// adds illness
/// shows illness 
/// edits illness
/// </summary>
namespace HealthDataBase.Controllers
{
    public class DoctorController : Controller
    {
        private IillnessInterface _illRepo;

        public DoctorController(IillnessInterface illRepo)
        {
            _illRepo = illRepo;
        }
        // GET: Doctor
        public ActionResult DoctorHome()
        {
            ViewBag.docName = Session["DocName"];
            return View();
        }

        public ActionResult IllnessView()
        {
            Session["illAuth"] = true;
            Session["illnessList"] = _illRepo.illnessTable;
            return View("IllnessView");
        }

        public ActionResult EditIllnessInfo(int IllnessId)
        {
            illness ill = _illRepo.illnessTable.FirstOrDefault(u => u.IllnessId == IllnessId);
            if (ill != null)
            {
                return View(ill);
            }
            return RedirectToAction("IllnessView");
        }
        [HttpGet]
        public ActionResult AddNewIllness()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddNewIllness(illness illness)
        {
            if (ModelState.IsValid)
            {
                _illRepo.saveIllness(illness);
            }
            return RedirectToAction("DoctorHome");
        }

        public ActionResult SaveIllness(illness illness)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form["_btnSubmit"] == "Save Info")
                {
                    _illRepo.saveIllness(illness);
                }
                else if (Request.Form["_btnSubmit"] == "Delete Illness")
                {

                    _illRepo.DeleteIllness(illness.IllnessId);
                }
            }
            return RedirectToAction("IllnessView");
        }
    }
}

HealthDataBase/HealthDataBase/Views/Admin/AddNewUser.cshtml
@using HealthDataBase.Domain.Entities
@model users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <title>Add New User</title>
</head>
<body>
    @RenderPage("_defaultPage.cshtml")
        <div class="panel panel-success">
            <div class="panel-heading text-center">
                <h4>Add User</h4>
            </div>
            <div class="panel-body text-center">
                @using (Html.BeginForm("AddNewUser", "Admin"))
                {
                    @Html.ValidationSummary()
                    <div class="form-group col-md-5">
                        <label>User Name:</label>
                        @Html.TextBoxFor(i => i.UserName, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Password:</label>
                        @Html.TextBoxFor(i => i.UserPassword, new { @type = "password", @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>First Name:</label>
                        @Html.TextBoxFor(i => i.FirstName, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Last Name:</label>
                        @Html.TextBoxFor(i => i.LastName, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Emailaddress: </label>
                        @Html.TextBoxFor(i => i.EmailAddress, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Phone Number:</label>
                        @Html.TextBoxFor(i => i.PhoneNumber, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>User Type:</label>
                        @Html.DropDownList("UserType", new SelectList(Enum.GetNames(typeof(TypeOfUsers))), "Select User Type", new { @class = "form-control" })
                    </div>
                    <div class="text-center">
                        <input type="submit" value="Add User" class="btn btn-success" />
                    </div>
                }
            </div>
        </div>
</body>
</html>

HealthDataBase/HealthDataBase/Views/Admin/AdminHome.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AdminHome</title>
    
    <script src="~/scripts/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="~/Content/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script src="~/scripts/bootstrap.min.js"></script>
</head>
<body>
    @if (ViewBag.isAdmin == true)
    {    
        @RenderPage("_defaultPage.cshtml")
        <div>
            <h1>Welcome to the Admin's Portal @ViewBag.adminName</h1>
            <div class="btn btn-default">
                @Html.ActionLink("Add New User", "AddNewUser")
            </div>
            <div class="btn btn-success">
                @Html.ActionLink("View Current Users", "ViewUsers")
            </div>
            
            
            
        </div>

    }
    else
    {
        @:Please enter your proper credentials to access this page.
    }

</body>
</html>

HealthDataBase/HealthDataBase/Views/Admin/EditUserInfo.cshtml
@using HealthDataBase.Domain.Entities
@model users

@{
    Layout = null;
}

<!DOCTYPE html>


    @RenderPage("_defaultPage.cshtml")
    <div class="panel panel-success">
        <div class="panel-heading text-center">
            <h4>Add User</h4>
        </div>
        <div class="panel-body text-center">
            @using (Html.BeginForm("SaveUser", "Admin"))
            {
                @Html.ValidationSummary()
                @Html.HiddenFor(model => model.UserId);
                <div class="form-group col-md-5">
                    <label>User Name:</label>
                    @Html.TextBoxFor(i => i.UserName, new { @class = "form-control" })
                </div>
                    <div class="form-group col-md-5">
                        <label>Password:</label>
                        @Html.TextBoxFor(i => i.UserPassword, new { @type = "password", @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>First Name:</label>
                        @Html.TextBoxFor(i => i.FirstName, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Last Name:</label>
                        @Html.TextBoxFor(i => i.LastName, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Email Address: </label>
                        @Html.TextBoxFor(i => i.EmailAddress, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>Phone Number:</label>
                        @Html.TextBoxFor(i => i.PhoneNumber, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-5">
                        <label>User Type:</label>
                        @Html.DropDownList("UserType", new SelectList(Enum.GetNames(typeof(TypeOfUsers))), "Select User Type", new { @class = "form-control" })
                    </div>
                    <div class="text-center">
                        <input type="submit" name="_btnSubmit" value="Save Info" class="btn btn-success" />
                    </div>
                    <div class="text-center">
                        <input type="submit" name="_btnSubmit" value="Delete User" class="btn btn-danger" />
                    </div>
            }
        </div>
    </div>

HealthDataBase/HealthDataBase/Views/Admin/ViewUsers.cshtml
@using HealthDataBase.Domain.Entities

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <title>ViewUsers</title>
</head>
<body>
    @RenderPage("_defaultPage.cshtml")
    @if (Session["auth"] != null)
    {

            <div class="container">
                <table class="table table-condensed text-center">
                    <thead>
                        <tr>
                            <th>User Id</th>
                            <th>User Name</th>
                            <th>User Password</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email Address</th>
                            <th>User Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{IEnumerable<users> _userlist = Session["userList"] as IEnumerable<users>;  }
                        @foreach (users user in _userlist)
        {
                            <tr>
                                <td>@Html.ActionLink(user.UserId.ToString(), "EditUserInfo", new { user.UserId })</td>
                                <td>@user.UserName</td>
                                <td>@user.UserPassword</td>
                                <td>@user.FirstName</td>
                                <td>@user.LastName</td>
                                <td>@user.EmailAddress</td>
                                <td>@user.UserType</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            @:Please Enter the proper credentials before accessing this page
         }

    
    


</body>
</html>

HealthDataBase/HealthDataBase/Views/Admin/_defaultPage.cshtml
@using HealthDataBase.Domain.Entities
@model users

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/scripts/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="~/Content/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script src="~/scripts/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
          $("#search").autocomplete({
              source: function (request,response) {
                  //debugger;   
                  $.ajax({
                      url: '@Url.Action("auto","Home")',
                      dataType: 'json',
                      method: 'POST',
                      data: { Prefix: request.term },
                      success: function (data) {
                          response($.map(data, function (item) {
                              return { label: item, value: item }
                          }))
                      }
                  });
              }
          })});
    </script>

</head>
<body>
    @{ users userEntity = Session["User"] as users;}
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#nbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div>
                    <a class="navbar-brand" href="#"><p>Health Center</p></a>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="nbar">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Home", "index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "AboutUs", "Home")</li>
                    <li>@Html.ActionLink("Near By Clinics", "NearByClinics", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "ContactUs", "Home")</li>
                    @if (userEntity.UserType == TypeOfUsers.User)
                    {

                        if (Session["LoginState"] != null)
                        {
                            <li>@Html.ActionLink("Acount page", "UserHome", "User")</li>
                        }
                    }
                    @if (userEntity.UserType == TypeOfUsers.Admin)
                    {
                        if (Session["LoginState"] != null)
                        {
                            <li>@Html.ActionLink("Acount page", "AdminHome", "Admin")</li>
                        }
                    }
                    @if (userEntity.UserType == TypeOfUsers.Doctor)
                    {
                        if (Session["LoginState"] != null)
                        {
                            <li>@Html.ActionLink("Acount page", "DoctorHome", "Doctor")</li>
                        }
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["LoginState"] != null && (Session["LoginState"] as bool?) == true)
                    {
                        <li><a data-toggle="modal" data-target="#USERPOP" href="#"><span class="glyphicon glyphicon-tower"></span>@Session["UserName"]</a></li>
                        <li><a href="@Url.Action("LogOut","User")"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                    }
                    else
                    {
                        <li><a data-toggle="modal" data-target="#SignUpPOP" href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>


                        <li><a data-toggle="modal" data-target="#LOGINPOP" href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

                    }



                </ul>
            </div>
        </div>
    </nav>
    <div class="modal fade" id="SignUpPOP" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Sign Up</h4>
                </div>
                <div class="modal-body">
                    <div class="container" style="width:400px; margin:auto;">
                        @using (Html.BeginForm("SignUp", "Home"))
                        {
                            <div class="form-group">
                                <label>First Name</label>@Html.TextBox("FirstName", "", new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>@Html.TextBox("LastName", "", new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                <label>Email Address</label>@Html.TextBox("EmailAddress", "", new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Phone Number</label>@Html.TextBox("PhoneNumber", "", new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label>Username</label>@Html.TextBox("UserName", "", new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Password</label>@Html.TextBox("UserPassword", "", new { type = "password", @class = "form-control" })
                            </div>
                            <div>
                                <input class="btn btn-success" type="submit" name="_btnSignup" value="Sign Up" />
                            </div>
                        }
                    </div>
                </div>
                <div class="modal-footer">
                    <p class="text-center text-danger">@ViewBag.error</p>
                    <button type="button" class="btn btn-default text-center" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
    <div class="modal fade" id="LOGINPOP" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Login</h4>
                    @using (Html.BeginForm("LogIn", "Home"))
                    {
                        <div class="form-group">
                            <label>Username</label>@Html.TextBox("username", "", new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Password</label>@Html.TextBox("password", "", new { type = "password", @class = "form-control" })
                        </div>
                        <div>
                            <input class="btn btn-success" type="submit" name="_btnLogIn" value="Log In" />
                        </div>
                    }
                    <div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="USERPOP" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">@userEntity.FirstName</h4>
                    <p>User Info: @userEntity.LastName</p>
                    <p>User Type: @userEntity.UserType</p>
                    <p>User Phone Number: @userEntity.PhoneNumber</p>
                    <div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="USERPOP" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                    <h4 class="modal-title">@userEntity.FirstName</h4>
                    <p>User Info: @userEntity.LastName</p>
                    <p>User Type: @userEntity.UserType</p>
                    <p>User Phone Number: @userEntity.PhoneNumber</p>
                    <div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



</body>
</html>